### ISSUE TITLE
可否为扩展添加选项功能 “右键添加Charset” 以便能够选择是否勾选该选项？

### ISSUE THREAD

**Issue by catshitz** [jinliming2/Chrome-Charset#1]
如题，转码时可直接点击扩展图标，且不影响需要右键转码者的使用（保持默认选项内勾选“右键添加Charset”即可）。

**Comment by jinliming2** [comment]
你的意思是，在扩展程序中添加选项页面，可以设置是否显示右键菜单的功能么？

**Comment by catshitz** [comment]
是的，如果可以的话就会方便些了，谢谢。

**Comment by jinliming2** [comment]
但是如果仅仅是增加一个开关功能就提供整个设置选项页面貌似是有点浪费，整个页面上只有一个选项按钮。。。

我觉得是不是可以直接将设置选项放在扩展图标的弹出页面的最底部，也不影响使用，需要设置时滚动到底部就行。

**Comment by catshitz** [comment]
那样就更好了，多谢！

**Comment by jinliming2** [comment]
已加入设置功能

**Comment by catshitz** [comment]
非常感谢！
