### ISSUE TITLE
最新的Release中option.html文件缺失

### ISSUE THREAD

**Issue by gtbl2012** [jinliming2/Chrome-Charset#11]
最新release的crx文件中（包括Chrome Web Store上的版本）似乎没有打包option.html，导致chrome无法安装该扩展。

经测试向软件包重新添加该文件或修改配置文件取消对该页的调用后，能正常安装。

**Comment by jinliming2** [comment]
感谢反馈，今天下午注意到这个问题，已重新打包并更新版本。
