### ISSUE TITLE
how to handle CRX_HEADER_INVALID?

### ISSUE THREAD

**Issue by yumuchen8** [jinliming2/Chrome-Charset#12]
when i drag the crx to extersion page. it happened CRX_HEADER_INVALID
![image](https://user-images.githubusercontent.com/12460488/56874008-4861f380-6a69-11e9-9c7d-15476f77600b.png)

pls tell me how to fix it .(i don't want to decompression the crx file.)

**Comment by jinliming2** [comment]
Hello, I googled this error, seems like Chrome 73 started using CRX3 format and disabled old version of CRX files.
I uploaded the CRX3 format of the latest version, pls have a try.

**Comment by jinliming2** [comment]
I will close this issue now, if you still got the same issue after downloading the crx3 version, please reopen it.
