### ISSUE TITLE
win7 x64 chrome 74下载了Chrome-Charset-V0.5.2 CRX3 VERSION，安装仍然出现错误CRX_HEADER_INVALID

### ISSUE THREAD

**Issue by juejian** [jinliming2/Chrome-Charset#15]
chrome 74 win7 x64下载了Chrome-Charset-V0.5.2 CRX3 VERSION，安装仍然出现错误CRX_HEADER_INVALID。

但在chrome浏览器**扩展程序**中，打开开发者模式，下载V0.5.2的源代码，选择**加载已解压的扩展程序源码**选项虽然可以安装，但是鼠标右键没有**编码**选项。每次只能点击菜单栏的Chrome-Charset图标进行操作。

源代码解压安装图：

![image](https://user-images.githubusercontent.com/12257223/62546030-5956a800-b895-11e9-80d0-c8eced9f741d.png)

菜单栏图标点击图示：

![image](https://user-images.githubusercontent.com/12257223/62546324-d8e47700-b895-11e9-8267-468bb1ae83e4.png)

是不是源码打包时出了bug 还是在win7 x64 chrome 74 x64bit上的兼容问题？

**Comment by jinliming2** [comment]
CRX3 的包我在 Chrome 76 测试通过。

确认一下安装过程：进入扩展管理页面（chrome://extensions/），开启右上角的开发者模式，**然后刷新扩展管理页面**，再把 CRX3 文件拖放到界面上进行安装，安装成功后可关闭开发者模式。

鼠标右键菜单需要在 菜单栏图标 右键 -> 选项 里手动开启。

**Comment by juejian** [comment]
问题已解决，谢谢！
