### ISSUE TITLE
纯js怎么不支持转换呢？

### ISSUE THREAD

**Issue by myvipbackup2** [jinliming2/Chrome-Charset#2]
如果打开一个纯js的页面   如 baidu.com/xxx.js  这样的页面，中文显示乱码但是不支持调整文本编码为UTF-8呢？没有反应

**Comment by jinliming2** [comment]
纯js目前是不支持的。

如果有需求的话我可以添加这个功能（不过得先调研一下可行性。。。）

请问你说的纯js的页面是指直接查看js源代码的页面，还是使用ReactJS之类编写的网站呢？（个人目前理解是前一种）

**Comment by jinliming2** [comment]
你好，我刚刚测试了一下，使用现有的插件代码是可以直接支持转换js文件编码的。
请问你可以提供一个转换无效的页面给我测试一下吗？

**Comment by myvipbackup2** [comment]
@jinliming2  你好，比如这个  http://webresource.c-ctrip.com/ResTourOutieOnline/R9/js/vacation/app/search_3_0/search_3_0.js  中文就是乱码不管怎么设置都没用，Mac OS Chrome 61

**Comment by jinliming2** [comment]
你好，我定位到问题了，已经提交代码，请等待Chrome商店更新吧~
