### ISSUE TITLE
'cannotLoadLocalFile' dialog shows every time I open a local file

### ISSUE THREAD

**Issue by szliu-a** [jinliming2/Chrome-Charset#23]
I understand that if I don't give the permission, this extension won't work on local files. But it is annoying to see this warning every time I open a local file. Can you add an option to turn it off?

**Comment by jinliming2** [comment]
Will fix in v0.5.5

**Comment by jinliming2** [comment]
v0.5.5 already published in Google Chrome Web Store.
Got some issues in Microsoft Edge Web Store, the extension for Edge will publish in a few days later.

If you still got this issue, please reopen it.
