### ISSUE TITLE
中文Chrome右键菜单无法显示中文

### ISSUE THREAD

**Issue by flyfanc** [jinliming2/Chrome-Charset#3]
使用中文Chrome时，右键菜单依然无法显示中文，还是显示Charset，望解决

**Comment by jinliming2** [comment]
是指菜单显示为`Charset`英文，还是菜单里的各个项目（那些国家地区名称）也是英文？
菜单名显示为`Charset`，不是个Bug，而是“特性”，因为插件的名字就叫“Charset”，没有中文名字。。。

**Comment by jinliming2** [comment]
Notice: this issue has been closed because it has been inactive for 732 days.
You may reopen this issue if it has been closed in error.
