### ISSUE TITLE
可以增加ISO8859-1 编码吗

### ISSUE THREAD

**Issue by Yihy** [jinliming2/Chrome-Charset#4]
可以增加ISO8859-1 编码吗

**Comment by jinliming2** [comment]
`ISO-8859-1` 编码目前在浏览器中都是以 `Windows-1252` 来实现的。所以即使我加入了 `ISO-8859-1`，浏览器也会自动表示为 `Windows-1252`。
`ISO-8859-1` 比 `Windows-1252` 多了几个控制字符（就是看不见的字符，用来控制文本输出用的），这几个控制字符会被显示为方框或问号，所以 HTML5 要求浏览器以 `Windows-1252` 来显示 `ISO-8859-1`。

详情参考 [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252)。

**Comment by Yihy** [comment]
明白了，谢谢你。
