### ISSUE TITLE
修改编码后，丢失原页面格式

### ISSUE THREAD

**Issue by DimonHo** [jinliming2/Chrome-Charset#5]
默认编码时：
![image](https://user-images.githubusercontent.com/3371641/36576315-ce55fd06-188a-11e8-86cc-5865355e7588.png)

修改成utf8编码后：
![image](https://user-images.githubusercontent.com/3371641/36576321-d6935428-188a-11e8-98e1-0d35cfc77137.png)

**Comment by jinliming2** [comment]
这个是纯文本文件吗？

**Comment by DimonHo** [comment]
@jinliming2 
就是一个普通的properties资源文件

**Comment by jinliming2** [comment]
您好，已定位问题所在。准备修复。

感谢反馈！

**Comment by jinliming2** [comment]
已修复，可以通过商店更新了~
