### ISSUE TITLE
可以集成到CEF吗  望指导

### ISSUE THREAD

**Issue by Jesson029** [jinliming2/Chrome-Charset#6]

**Comment by jinliming2** [comment]
你好，非常抱歉，我对 CEF 这个项目并不熟悉，也许你可以看看他们的这个讨论：https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions 时间是在去年底，貌似他们才开始准备对扩展程序的支持。

**Comment by yjxsy1996** [comment]
不知道 我的servlet发送到jsp页面出现中文乱码是不是浏览器的原因呢 设置了其他的setCharacter也没有用

**Comment by jinliming2** [comment]
Notice: this issue has been closed because it has been inactive for 152 days.
You may reopen this issue if it has been closed in error.
