### ISSUE TITLE
是否可以支持设置默认编码？

### ISSUE THREAD

**Issue by Handsome08** [jinliming2/Chrome-Charset#8]
当前功能只能每次对某一个网页单独设置编码格式，是否可以像旧版chrome一样设置默认的编码格式？
这样浏览所有网页都使用默认的编码格式。

**Comment by jinliming2** [comment]
意思是一次设置，除非手动重置，不然永久对所有标签有效的吗？

**Comment by Handsome08** [comment]
> 意思是一次设置，除非手动重置，不然永久对所有标签有效的吗？

是的，不然现在chrome的默认编码一直是GBK，进入到乱码的页面都得重新设置下编码。希望可以直接修改chrome的默认编码，或者说在charset中设置默认编码，虽然chrome是GBK，但是每次进入一个页面之后charset就自动修改为charset中设置的默认编码。

**Comment by jinliming2** [comment]
已加入 v0.5.0 发布，请等待 Chrome 商店更新
